Removed pandas dependency
Macrometacorp/pyC8 pull request #93
Opened 2022-09-14 09:26 UTC by dlozina-macrometa

## Description

We have removed the pandas package dependency. We had an issue using the pyC8 driver(SDK) with AWS lambda.
Numpy (we introduce this transient dependency with pandas) has a lot of C extensions that we do not need

Fixes # (issue)

I removed pandas dependency and created the same data structure with a built-in csv package

Please delete options that are not relevant.

- [x] New feature/update (non-breaking change which adds functionality)

## How Has This Been Tested?

I have used the new driver(sdk) version to fill in documents from a file on my test account. (End-to-end test)

**Test Configuration**:

* C8 Version: Latest (from this branch)

## Reviews

Please identify two developers to review this change

- [ ] @ricardo-macrometa 
- [ ] @jyuwei 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added new functional tests that prove my fix is effective or that my feature works
- [ ] Existing and new functional tests pass with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-09-14 13:06 UTC, ricardo-macrometa requested changes
You also need to remove the dependency from the setup.py and requirements.txt

2022-09-14 13:11 UTC, dlozina-macrometa commented
Sure, thanks! I haven't seen pandas in requirements.txt in the repo. I will remove it from `setup.py`. 🙏 @ricardo-macrometa

2022-09-14 18:56 UTC, ricardo-macrometa approved these changes

2022-09-16 17:23 UTC, jyuwei approved these changes

2022-09-16 17:24 UTC, merged